### ISSUE TITLE
Speed comparison with other data processing packets

### ISSUE THREAD

**Issue by XianglinZhang-risker** [hope-data-science/tidyfst#2]
Hello teacher, can you provide a table with speed comparison with tools like pandas, data.table, dplyr?

**Comment by hope-data-science** [comment]
Thank you for the comments, this is in the TODO list at version 1.0.0, when I am very satisfied with all the API and the performance of the underlying codes. By then, you'll get a rather stable version of tidyfst, and be able to use it even in industry.

'tidyfst' is making copies all the time, this is hurting some performance, but it is much safer for analysis. If you want absolute performance, I am now making another package named 'tidyft'. Check it in <https://github.com/hope-data-science/tidyft>.

**Comment by XianglinZhang-risker** [comment]
Thank you for your prompt response. May I ask what is the difference between these two packages. Does tidyfst pay more attention to stability and tidydft pay more attention to performance?

**Comment by hope-data-science** [comment]
Absolutely. tidyfst has taken care of something invisibly, so it can deal with any data.frame (tibble/data.table/data.frame). It makes copies, so your data would not be modified, which is safe for reproducible analysis.

tidyft focus on performance, least time and space. When you know how to use it with the fst family (exists both in tidyfst and tidyft), it is rather safe too. But it assumes that all the data.frame are data.table. tidyft have removed the "_dt" suffix and looks just like 'dplyr' syntax, that's because you never use it with 'dplyr', and would not cause ambiguity. But you do have to use it with extra caution. If you know how to use tidyft correctly, it will give you the best performance ever.

**Comment by XianglinZhang-risker** [comment]
Fēicháng gǎnxiè nín, wǒ dàgài lǐjiěle,tidyft bǎochíle data.Table de tèxìng, suǒyǒu cāozuò dōu shì bùkěnì de, dànshì shǐyòngle dplyr de yǔfǎ shǐ yònghù yǒngyǒu gèng hǎo de tǐyàn, shì zhèyàng ba? Fēicháng gǎnxiè nín, wǒ huì chíxù guānzhù de, fēicháng gǎnxiè nín duì R shèqū de gòngxiàn! Zhù nín hǎo yùn!
展开
108/5000
Thank you very much, I probably understand, tidyft maintains the characteristics of data.table, all operations are irreversible, but using dplyr syntax to make users have a better experience, right? Thank you very much, I will continue to follow, thank you very much for your contribution to the R community! Good luck!
