### ISSUE TITLE
Can't create custom functions using tidyfst functions

### ISSUE THREAD

**Issue by markfairbanks** [hope-data-science/tidyfst#5]
Is it possible to create custom functions using `tidyfst` functions?

Custom function with `filter_dt()`:
``` r
library(tidyfst)

test_df <- data.table(x = 1:3, y = c("a", "a", "b"))

filter_fn <- function(.data, filter_col) {
  .data %>%
    filter_dt(filter_col == "a")
}

test_df %>%
  filter_fn(y)
#> Error in .checkTypos(e, names_x): Object 'filter_col' not found amongst x, y
```

Custom function with `mutate_dt()`:
``` r
add_one <- function(.data, add_col) {
  .data %>%
    mutate_dt(new_col = add_col + 1) 
}

test_df %>%
  add_one(x)
#> Error in eval(jsub, SDenv, parent.frame()): object 'add_col' not found
```

The normal eval/substitute workflow that works with `data.table` doesn't seem to work in tidyfst.

``` r
library(data.table)
library(magrittr)

dt_add_one <- function(.data, add_col) {
  
  .data <- copy(.data)
  
  add_col <- substitute(add_col)
  
  .data[, new_col := eval(add_col) + 1][]
}

test_df %>%
  dt_add_one(x)
#>    x y new_col
#> 1: 1 a       2
#> 2: 2 a       3
#> 3: 3 b       4
```

**Comment by hope-data-science** [comment]
This is a very good question. At the very beginning *tidyfst* was only supposed to be used on the top for data manipulation, so I use some tricks to facilitate the design, but cause some functions could not be reused in self-defined functions and packages. But since you have proposed this, I think some users actually need this and I will fix it in the next released version. This has something to do with the non-standard evaluation and could be fixed. I'll checked these functions and make them work.

Thanks.

**Comment by hope-data-science** [comment]
After further investigation, I think it is just another way to realize it but not a problem inside *tidyfst*. I'll give you a working example:

```
library(tidyfst)
#> 
#> Life's short, use R.

test_df <- data.table(x = 1:3, y = c("a", "a", "b"))


add_one = function(.data,add_col){
  
  substitute(add_col) %>% deparse() -> add_col
  
  eval_string = stringr::str_glue("
        .data %>% 
  mutate_dt(new_col = {add_col} + 1)          
                  ")
  
  eval(parse(text = eval_string))
  
  
}

test_df %>% add_one(x)
#>        x      y new_col
#>    <int> <char>   <num>
#> 1:     1      a       2
#> 2:     2      a       3
#> 3:     3      b       4

```

Thank you anyway for giving comments to this very package.
